# В этом файле указывается список контестов,
# которые нужно автоматически обновлять после каждого пуша в репозиторий.
#
# Пример:
#
#
# contests:
#   9_strings: [511211]
#   8_bintree: [511208, 511209]
#
#
# 9_strings, 8_bintree       название файла с описанием контеста без расширения,
#                            сам файл лежит в папке contests
#
# 511211, 511208, 511209     номер контеста на сервере

contests: {}