dist: trusty
sudo: false
language: python
python:
- '3.6'
install: pip install -r requirements.txt
script:
- python ./contest.py generate-tests -f -j5
- python ./contest.py validate
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: inup5eIGYFd0XrYJlkxXnoe6JLlTAAOYGYiDAjlPVAd1cjaIs0fdkWMzqxM1/fK6O2TfpskJLkjb8weRNe6U53Lyh8SXz7veZleo6T4/9nR19V62CvIgHhuiwIDf9/TLdRGsccljYyIdYt5CQBwOt7m1R/o+dC9dJb2PTs/zrXWpS4vOjO34JxWOCRaBi3SKdNbkAvWjdtD16wlhuxsV/5Rof3R8kmG8ZWxEk4QOjc1pX3TVaXPIcb1cvwU3SZYEtJvYfHDb4ZWr1cVVrHaXbaRtMWuZolhu/j5L1dwqhw3wT7pMojckDuRrtJkE5bpkF1Hz5svEQq80WlCf5lt7NhwqcpCGZ5GHZAPitZu7DDkZ1gH8bkMjzdsUNGZW2ZSJJrvlKDNArf/bFF0IBGkH4+5g8Wbg4t08g4wfCCIZCmM6PwscaSY7x93DdaMWzo2FgqKPd82Cl41hQdxjguUQYPMD7lDyO/BqNE8xL1SYPWb1eKLOKIetlPdeK9CCZLGuZ91yjELKAbkmm/TDvfMrjwHLq5bKgQPQ1rrMTBd5cXeNPPLAwm5Nkr07K7bqBuPUZB8Y2izrrhg6XuD6GSI5glzyhOSQrBQ7CaqRWEyqY6X4qWiKBDNtr2mzUAPAfZ4Nme4ntwMq1wN6o/rnrcBa9ffC8Q18QyT3OeNOiGTpT40=
