dist: trusty
sudo: false
language: python
python:
- '3.6'
install: pip install -r requirements.txt
script:
- python ./contest.py generate-tests -f -j5
- python ./contest.py validate
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: rXCzNbPP3fgS84Ue2pj+Mo6AtYkS43OjMDBsdJMRPmym36TfXTRbtJ/9jlqOd88eQFgaYof2zT8VtUKRC4PecvdoKNe0VTc7gdp2Gk61Qt73da28HEAPfNDkPW1ScqHCD6HsXf+izF2LRMvCQ5l6r+i0fIsJTn2vwimtAzKD6Oi3HXRyJBsxf3hQirKQfso23rshnQc0EEhBBIetla8FyxESuehM5Hzx60mhRI8WbhSkp22T6Y89+3eRznBqd6uNKwAg7wKwP3j5o6YVdRE7qBjnYKlEt3kDH8BDT5gMp+C4vQQkmsGClvCeSznZgsOd0Zvc/yhxjkwoZVzplEKk8dQK3eE4gKaWdIRhvSRO97Qd1q9M35cvOFB4S6atkdBc29WDcuXm7B2c3fZGF6DgGh2XCdb967PyYypbY7Nfr6Amw49FMINfH+mR2X4EyW1U5+DJw/QR6rBN8oYlofFFH8oesIqhK0h0dlW0A45LUfazua7Wa0Iw8VZqBtFmsjLc0glVoNUL5fDG9WxikqXu4VBLemZsRzdQwYhtj3/tYY5h6fYbN0F6t0CVqXJSy6d5MwBzamU79qv89KqsVOu1bvfIZyCRSeP4jacgKmCcaCy+I2dxSy621pK2beGpeIY70HzRHI9I1PwrR3qrxy/rP0XolZeBkwhL1L9qTV+Fo8k=
      - secure: RH99NesYbUgr993NPWlFNal6N/559H9y52WGw9QXJ+M/kAiTLrJWtnzPMoX5t7Si3uTr51dFQW6inGRVRvv9D/Rb0a3zwWi4bgB3dVHpvsw7Lg5qa8u6bjs8TbuVCw8Uoak8yQNX6C4z8pXB5u/wbTZorEQp2nlqRDkt+Xan9Q056HgW8rDQrQVePBee5OO5OEEEs58bVebeSPz9JjxITGesLlMb/dF8Mtm5mZUoaCfYguxHQCAO9KfF2iQEXoAs2LCYsmBrc6H2rihS8tVjl+HUA35kPhZQ60nsfl7s/NDm6/Vm2+kcFHmDEd/wjD9n+coTFEFaFZu5vvsZ2CVBYmWxPdVABi7kbEkMJ6O+rvunFv+nfDMyD5b5DA8wYRXG8A73LiVjdMQ4VgJNHcHFoTPx6BMkYSRuGCMBnQ/3EwpFJK02L38g2SLLR98P+u9f3Lw8+MHfzvLrjAWtdi9Peu0j+79T3w/iWdnKTTy7Kf8gYTrytLTAF671ni77/bodfBSNDnlIMg4Fli4tyXKG5rN8KJpgC0YYEpRXU80g7ahwjjXhT7omKIQGouRzJ8VBwEIiY3sdHxF256oaofcgOA7QkcOns+51uOB3oG1PLMKgTnhzDejpymv3eRPYgHlP0TFW7Gzc/mZnmgxn/7sCxBZ8w9PupL7+05FDcnjBQ4E=
