dist: trusty
sudo: false
language: python
python:
- '3.6'
install: pip install -r requirements.txt
script:
- python ./contest.py generate-tests -f -j5
- python ./contest.py validate
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: hA6DgI1Uuy431vxMWoAUxOhNGM2fkQgLi3djoe5Gni3D/p08rm4GXXFckA8RsWXPgucvvwzWJdq7r7DLSRMseyenq+oQ+BZEuOkpH1O47lQFzjMTMwnk1wWZMB4vQo4QpsC4WdKuvo3yjPAokkDLO3roH/+MCA4n2TcDFY8HPSdvcftlfiI2EnCzF7VczygDAKKwQ9yPm+0NaI5+q0ZSOvxCXczl0q4x+6rysV3DBPVReAXNJ/8MRXOV73WuyJ+x7qe5eh0rDxsINFdmsvONhbvGuqJrNl3XQCduDPPCPJxdjkg58USjy+lLr2LxSeV0vyPpN75IrE7Jh9cMCYfAr0gfNLJ4OdJWEKz7UyxiQ/lFblt2QHrPVPH9g3ztDT0236w4qBZRXBu66eKwZhAnrY0QsjKT+xEHYFcn5uGB1PuMFnYAGFVU9LGHKC7Fg4JSKAreTswbZcBDJVeEUTyBqt/chZaQpXihJB6NGmcTZtG3gGdEWSyQYClqhVcJmKG9SSY7U2STr7xDpf0UzMm6boPQSiSkGUq9S9aXc45/r/IwhJgRqiJ1WJPaliILHLZGTp0YbkBxS9FJR4kY5LxGJpIRGNWqg5vzn2KO83SsK0bsrreg6j8i4TUkIczmEPuRWWR/6ew51eLdGYWE3G3N9yjiYoOZhA4O8CUzU4MM0Us=
