from lib.testgen import TestSet

tests = TestSet()
tests.add('2 GGAAAGGGTCCAAAGAACCCAGTC GACTGGGTTCTTTGGACCCTTTCC','[]\n')
tests.add('1 AGTCACCTGTTGACAGTAGTCCTTACCATGGTTTTACCTGAAACTTTTCCAGGGTGA\n', '[TCACCCTGGAAAAGTTTCAGGAAAAGGACCTGTCAACAGGTGACT]\n')
tests.add('10 GGG ACC GGA TCC GGG ACT GGA TGG CCT AGA\n', '[TCCCAGTCTCCC]\n')
tests.add('6 GGGA TCCA GGAA TCCA GGGA TCTT\n','[AACCTGGTCCTC]\n')
tests.add('3 GGAAAGGGT ACCAACCAC GGGAAAAAA\n', '[TTTTTTCCTGGTTCTTTCC]\n')  
tests.add('32 A T A T C G T C G A T G T A T A T G T C T G C T C A T A C T A G\n', '[TGAAGACACA]\n')
